services:
  api:
    build: .
    restart: always
    ports:
      # Altere para a porta que você deseja expor
      - "8080:8080"
    environment:
      # Altere para o endereço do front end
      REQUEST_HOST: http://localhost:5000
    depends_on:
      - db

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: watermelon_db
      MARIADB_USER: watermelon
      MARIADB_PASSWORD: watermelon
    volumes:
      - data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  data:
